import js from '@eslint/js';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    ignores: [
      'types/**',
      'src/types/global.d.ts',
      'src/types/advanced-types.ts',
      'src/types/error.ts',
      'src/types/*.d.ts',
      'node_modules/**',
      'public/service-worker.js',
      'dist/**',
      'build/**',
      '.storybook/**',
      '.chromatic/**',
      '__mocks__/**',
      'config/**',
      'tests/**/*.js',
      'tests/**/*.mjs',
      'scripts/**',
      '**/*.mjs',
      '*.mjs',
      'src/utils/ci-workflow.js',
      'src/pages/PlaygroundPage.tsx',
      'src/components/VersionHistoryComparer.tsx',
      'src/components/ui/sidebar.tsx',
      'src/components/AIConsistencyCheckerEnhanced.tsx',
      'src/theme/ThemeProvider.test.tsx',
      'src/theme/__tests__/ThemeProvider.test.tsx',
      'src/tests/setup.ts',
      'src/tests/e2e/performance-lhci.spec.ts',
      'src/stores/__tests__/index.test.ts',
      'src/security/__tests__/XSSProtection.test.tsx',
      'src/resource-optimization/resource-preloader.ts',
      'src/pages/TokensPage.tsx',
      'src/pages/TokenManagerPage.tsx',
      'src/pages/OverviewPage.tsx',
      'src/types/plugin.ts',
      'src/pages/ComponentsPage.tsx',
      'src/pages/BuildSettingsPage.tsx',
      'src/monitoring/performance.ts',
      'src/core/PluginManager.ts',
      'src/core/ErrorLogger.ts',
      'src/core/DocumentSyncer.ts',
      'src/core/DocumentMapper.ts',
      'src/components/VirtualList.tsx',
      'src/components/VirtualGrid.tsx',
      'src/components/ui/chart.tsx',
      'src/components/ThemeToggle.tsx',
      'src/components/Table.tsx',
      'src/components/StorybookSettingsPanel.tsx',
      'src/components/ResponsiveImage.tsx',
      'src/components/ResourcePreloadingExample.tsx',
      'src/components/Menu.tsx',
      'src/components/LanguageSwitcher.tsx',
      'src/components/Input.tsx',
      'src/components/ImageOptimizationExample.tsx',
      'src/components/GenericComponent.tsx',
      'src/components/FormError.tsx',
      'src/components/Form.tsx',
      'src/components/FontOptimizationExample.tsx',
      'src/components/Dropdown.tsx',
      'src/components/CustomAnimation.tsx',
      'src/components/ColorSchemeBatchGenerator.tsx',
      'src/components/AnimatedEnhanced.tsx',
      'src/components/AIPerformanceOptimizer.tsx',
      'src/components/AIComponentRecommender.tsx',
      'src/collaboration/sync.ts',
      'src/collaboration/multi-user.ts',
      'src/collaboration/conflict-resolver.ts',
      'src/cli.js',
      'src/ai/version-history-comparer.ts',
      'jest.setup.ts',
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 2020,
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.es6,
        ...globals.node,
        ...globals.jest,
        RequestInit: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescriptEslint,
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      ...typescriptEslint.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...prettier.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-useless-assignment': 'off',
      '@typescript-eslint/no-throw-literal': 'off',
      'no-console': ['warn', { allow: ['warn', 'error', 'log'] }],
      'react-hooks/rules-of-hooks': 'warn',
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/refs': 'off',
      'no-case-declarations': 'warn',
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/purity': 'warn',
      'no-unused-vars': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    files: ['**/*.test.{ts,tsx}', '**/__tests__/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['src/utils/ci-workflow.js'],
    rules: {
      'no-undef': 'off',
      'no-template-curly-in-string': 'off',
      '@typescript-eslint/no-undef': 'off',
    },
  },
  {
    files: ['src/utils/performance-reporter.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    files: ['src/utils/lazy-loader.tsx'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['**/*.js', '**/*.jsx', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es6,
        ...globals.node,
        ...globals.jest,
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        describe: 'readonly',
        test: 'readonly',
        it: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterAll: 'readonly',
        afterEach: 'readonly',
        expect: 'readonly',
        jest: 'readonly',
      },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...prettier.rules,
      'no-undef': 'off',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
];
