module.exports = {
  'color.primary': '#e06a70',
  'color.background': '#1a1a1a',
  'color.card': '#2d2d2d',
  'color.destructive': '#ff6b5b',
  'color.ring': '#ff9f9a',
  'color.foreground': '#f0f0f0',
  'color.muted-foreground': '#a0a0a0',
  'radius.default': '0.5rem',
  'radius.sm': '0.125rem',
  'radius.md': '0.25rem',
  'radius.lg': '0.5rem',
  'shadow.card': '0px 6px 20px -4px #0a0a0a',
  'shadow.popover': '0px 10px 30px 0px #0a0a0a',
  'shadow.focus': '0px 0px 0px 2px #e06a70',
  'typography.font-sans': 'Geist, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial',
  'typography.font-serif': 'Source Serif 4, Georgia, "Times New Roman", serif',
  'typography.font-mono': 'Geist Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, "Roboto Mono", "Courier New", monospace',
  'font-size.heading-1': '2rem',
  'font-size.heading-2': '1.5rem',
  'font-size.body': '1rem',
  'font-size.caption': '0.875rem',
  'line-height.heading': '1.2',
  'line-height.body': '1.5'
};
